<?php //if (!$this->blog) { ?>
<br/>
<h2 style="padding-left: 8px;">Atividades<br /></h2>
<h3 style="padding-left: 8px;">Clique em uma atividade para ver mais detalhes e se inscrever.</h3>
<h3 style="padding-left: 8px;color: #9ae;">Envie a sua <a style="color:#bcf;" href="/atividades/formulario">Proposta de Atividade</a>.</h3>
<br />

<ul id="menu">
<!--	<li>
		<a href="<?php echo $this->baseUrl(); ?>/atividades/formulario">Submeter proposta de trabalho</a>
	</li>-->
	<li>
		<a href="javascript:history.back();">Voltar</a>
	</li>
	<hr />
</ul>

<br />
	<hr style="border-bottom: 1px solid #fc9;">
	<div class="atividades clearfix">
		<h2 style="display: block;">08:00</h2>
		<h3>Credenciamento - Entrada do evento...</h3>
		<hr style="border-bottom: 1px solid #fc9;">
	</div>
	<div class="atividades clearfix">
		<h2 style="display: block;">09:00</h2>
		<h3>Abertura do Evento - Sala XXX</h3>
		<hr style="border-bottom: 1px solid #fc9;">
	</div>
    <?php
//}
	$horaini = 'x';
	$almoco = false;
	foreach($this->atividades as $atividade): 
    $qtInscricoes = isset($this->countAtividades[$atividade['id']]) ? $this->countAtividades[$atividade['id']] : 0;
    if (date('H:i', strtotime($atividade['hora_inicio'])) == '14:00' and $almoco == false) { ?>
		<?php if ($horaini != 'x') echo '</div>'; ?>
		<div class="atividades clearfix">
		<h2 style="display: block;">13:00</h2>
		<h3>Intervalo para Almoço</h3>
		<?php 
		$almoco = true;
		} 
	if ($horaini != $atividade['hora_inicio']) { ?>
		<?php if ($horaini != 'x') echo '</div>'; ?>
		<div class="atividades clearfix">
		<hr style="border-bottom: 1px solid #fc9;">
		<h2 style="display: block;"><?php echo date('H:i', strtotime($atividade['hora_inicio'])); ?></h2>
		<!--
		    <hr style="border-bottom: 1px solid #fc9;">
		 -->
		<?php 
		$horaini = $atividade['hora_inicio'];
		}
	 ?>
    <div class="lista_atividade" style="margin-left:10px;"  id="<?php echo "atividade_".$atividade['id']?>">
        <div class="titulo_atividade" ><?php echo $atividade['nome'] ?></div>
        <div class="palestrante_atividade">
        <b><?php echo $atividade['nome_usuario']?></b>
        </div>
		<span>Vagas: <?php echo ($atividade['qt_vagas'] - $qtInscricoes > 0)?(($atividade['qt_vagas'] - $qtInscricoes).' disponíveis.'):('Atividade Lotada'); ?></span><br>
		<b><span><?php echo ($atividade['nome_sala']); ?></span></b>
    </div>
    <?php $float_atividades = array($atividade); ?>
    <?php echo $this->partial('inscricoes/info_atividade.phtml', array('atividades' => $float_atividades,'idUsuario'=>Zend_Auth::getInstance()->getIdentity()->id)); ?>
    <?php endforeach; ?>
	<hr style="border-bottom: 1px solid #fc9;">
    <div class="atividades clearfix">
		<h2 style="display: block;">17:00</h2>
		<h3>Encerramento</h3>
	</div>
<script>
    $(document).ready(function(){
        $(".lista_atividade")
        .mouseover(function(){
            $(this).css("background","#f90");
        })
        .mouseout(function(){
            $(this).css("background","#fff");
        })
        .click(function(){
            showInfo($(this).attr("id"));
        })
        $("input:submit").click(function(){
            var id = $(this).attr("id").split("_")[1];
            cadastraInscricao(id,this)
        });
        $('.float_info .close').click(function(){
           	$(this).parents('.overlay').hide();
           	$('body').css('overflow','auto');
        	return false;
        });
    })
    function showInfo(id){
        $(".overlay").hide();
        $("#info_"+id).parent('.overlay').show();
        $('body').css('overflow','hidden');
    }
    function cadastraInscricao(id,field){
        var url = "<?php echo $this->baseUrl() ?>/inscricoes/cadastra";
        $.post(url,{id_atividade:id},function(data){
            alert(data);
        })
    }
</script>